### ISSUE TITLE
Review bin splitting, reweighting and shuffling code.

### ISSUE THREAD

**Issue by kandrosov** [cms-tau-pog/TauMLTools#10]
- Eliminate the necessity of creating binned tuples and produce shuffled root-tuple using root files produced by crab jobs.
- Add a possibility to select a subset of events based on the event id (e.g take only events with an odd event id).

**Comment by shedprog** [comment]
@kandrosov  When reviewing bin splitting I noticed the following thing: from what I see inside `tauTuple` variable - `sampleType` is always =0 (set to Data) it may provoke error at next steps I guess

**Comment by kandrosov** [comment]
> @kandrosov When reviewing bin splitting I noticed the following thing: from what I see inside `tauTuple` variable - `sampleType` is always =0 (set to Data) it may provoke error at next steps I guess

Are you using the latest version of the code? The corresponding issue https://github.com/cms-tau-pog/TauMLTools/issues/17 should have been fixed by this PR  https://github.com/cms-tau-pog/TauMLTools/pull/26 . Please, let me know if the issue is still present in some cases.
