### ISSUE TITLE
Conversion of DeepTauv2p5 graph to tensorflow 1.6 (for CMSSW_10_6_X)

### ISSUE THREAD

**Issue by shedprog** [cms-tau-pog/TauMLTools#123]
In order to document the current status of the conversion https://github.com/cms-tau-pog/cmssw/issues/166 and to speed up the process. 

Weights of the models are saved within tf==~~2.9~~2.8: https://github.com/shedprog/TauMLTools/blob/aae6aca098d8d281f335730c855289d4d7bf0b66/Training/python/split_network_2p5.py#L169

**1.14.00**
As current TF.version and tf==1.6.0 is quite inconsistent in terms of interface, I started from the latest version of tf 1 (1.14.0) which is still documented on the propriety level.
Adaptation for the NN: https://github.com/shedprog/TauMLTools/blob/coversion_tf1.6/Training/python/Training_CNN_tf1_14.py
Adaptation for splitting script: https://github.com/shedprog/TauMLTools/blob/coversion_tf1.6/Training/python/split_network_2p5_tf1_14.py
But still in this version TensorFlow algebra is not compatible with 1.6.0 (within CMSSW 10_6_X) and graph can not be interpreted.

**1.6.0**
After this with the gradual api rollback the model was build and weights copied from TF 2.9.
Adaptation for the NN: https://github.com/shedprog/TauMLTools/blob/coversion_tf1.6/Training/python/Training_CNN_tf1_6.py
Adaptation for splitting script: https://github.com/shedprog/TauMLTools/blob/coversion_tf1.6/Training/python/split_network_2p5_tf1_6.py

At the moment, there are some problems with conversion to the constant graph which related to non-availability of the output layer in the graph, to my feeling it might be related with mixing of the backends and not having graph in the session at all. Unfortunately, I did not find precise documentation of the graph compilation for exactly 1.6.0 so experiments with the deprecated api https://github.com/tensorflow/docs/tree/r1.6 are ongoing. Also, naming of the tensors out-of-box does not correspond to the cmssw, so identity to be fixed.
Graph conversion code: https://github.com/shedprog/TauMLTools/blob/aae6aca098d8d281f335730c855289d4d7bf0b66/Training/python/deploy_model_tf1_6.py#L67-L95

- [x] Saving weights in the tf==~~2.9~~2.8
- [x] Building (tf 1.6.0) environment 
- [x] Rollback of NN api
- [x] Rollback of splitting script
- [x] Saving split model within (tf 1.6.0) interface
- [x] Fixing soft for saving of (tf 1.6.0) model to *.pb graph
- [x] Fixing the output nodes names consistency
- [ ] Testing within cmssw
- [ ] Testing consistency of id scores vs. cmssw 12_4_X integration

**Comment by kandrosov** [comment]
Can model be split in TF 2.9 and still be compatible with 2.6? For DeepTau v2p1 deployment, I didn't modify the NN model code to be compatible with 1.6, but unfortunatelly I don't remember the details of how exactly I did the conversion...

**Comment by shedprog** [comment]
> Can model be split and frozen in TF 2.9 and still be compatible with 2.6? For DeepTau v2p1 deployment, I didn't modify the NN model code to be compatible with 1.6, but unfortunatelly I don't remember the details of how exactly I did the conversion...

Small correction to freeze and/or save weights I use 2.8 not ~~2.9~~ and it seems to be compatible with CMSSW_12_4_X both for deep tau and for my local tests.

About modifications: they come from mainly two aspects, 1) in 1.6 keras is standalone model and some fields are modified 2) change to older version of python

**Comment by shedprog** [comment]
Not resolved at the moment, because of incompatibility of graphs.

[byDeepTau2018v2p5VSeraw_score.pdf](https://github.com/cms-tau-pog/TauMLTools/files/9166845/byDeepTau2018v2p5VSeraw_score.pdf)

[byDeepTau2018v2p5VSeraw_score_delta.pdf](https://github.com/cms-tau-pog/TauMLTools/files/9166844/byDeepTau2018v2p5VSeraw_score_delta.pdf)

[byDeepTau2018v2p5VSjetraw_score.pdf](https://github.com/cms-tau-pog/TauMLTools/files/9166843/byDeepTau2018v2p5VSjetraw_score.pdf)

[byDeepTau2018v2p5VSjetraw_score_delta.pdf](https://github.com/cms-tau-pog/TauMLTools/files/9166842/byDeepTau2018v2p5VSjetraw_score_delta.pdf)

[byDeepTau2018v2p5VSmuraw_score_delta.pdf](https://github.com/cms-tau-pog/TauMLTools/files/9166840/byDeepTau2018v2p5VSmuraw_score_delta.pdf)
[byDeepTau2018v2p5VSmuraw_score.pdf](https://github.com/cms-tau-pog/TauMLTools/files/9166841/byDeepTau2018v2p5VSmuraw_score.pdf)
.

**Comment by shedprog** [comment]
.
