### ISSUE TITLE
TauTuple: store tracks

### ISSUE THREAD

**Issue by kandrosov** [cms-tau-pog/TauMLTools#3]

**Comment by shedprog** [comment]
As it was discussed several kinematic parameters and its quality was added to the tau-tuple. There are still few questions that should be clarified:
**1)** How economical we should be to the memory in this ntuple, I added just basic parameters that are listed in Isolated Track section here at [twiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2017#Isolated_Tracks) than plotting the correlation matrix I decided to remove few highly correlated variables:
![image](https://user-images.githubusercontent.com/31743376/88535565-d1702d80-d012-11ea-8170-bfaa5803fd07.png) and then I converged on the following list of parameters:

1. pt eta, phi, mass - 4-momentum of the track 
2. pfIsoCH,pfIsoNH,pfIsoPh, pfIsoPu - 4 components of isolation (charged hadron, neutral hadron, photon, pileup) 
3. fromPV -  the association to PV=ipv. >=PVLoose corresponds to JME definition,
                           >=PVTight to isolation definition:
                            NoPV = 0, PVLoose = 1, PVTight = 2, PVUsedInFit = 3 
6. pdgId -  PDG identifier 
7. charge -  electric charge 
8. dxy - signed transverse impact parameter wrt to the primary vertex 
9. dxy_error -  uncertainty of the transverse impact parameter measurement 
10. dz -  dz wrt to the primary vertex 
11. dz_error -  uncertainty of the dz measurement 
12. matchedCaloJetEmEnergy -  EM energies of the nearest calo-jet within dR=0.3
13. matchedCaloJetHadEnergy -  Hadronic energies of the nearest calo-jet within dR=0.3
14. isHighPurityTrack - isTightTrack, isLooseTrack - track Quality 
15. dEdxStrip - estimated dE/dx values in the strips 
16. dEdxPixel -  estimated dE/dx values in the pixels 
17. deltaEta, deltaPhi -  the difference in eta/phi between the initial track trajectory and
                                 the point of intersection with the Ecal.  Can be used to identify
                                 roughly the calorimeter cells the track should hit.
20. n_ValidHits -  number Of Valid Hits 
21. n_InactiveHits -  number Of Inactive Hits

Is something missing or should be removed from this list?

**2)** pat::IsolationTrack class has reference to the [hitPattern](https://github.com/cms-sw/cmssw/blob/CMSSW_9_2_4/DataFormats/TrackReco/interface/HitPattern.h) objects there are a lot of information there, however only general number of Valid Inactive Hits were added, other are empty or highly correlate with other. Should something be added here?

**Comment by kandrosov** [comment]
@shedprog thank you for preparing the list of variables to store!
Here are a few comments:
- "mass" of the track is not defined from physics point of view. It is probably set to a predefined value when `isolatedTrack` is produced from a `packedPFCandidate` => I propose to not store it.
- I'm not sure what `pdgId` means for the track probably same logic as for the `mass` => to be checked
- we already store collections of PF candidates, so PF isolation can be re-computed in the later stages (if we need it). Therefore, don't need to store `pfIso*`
- similarly, for `matchedCaloJet*Energy` - those are global variables for tau-jet and can be recomputed using PFcandidates, remove them.
- I think we can try to include more information from hitPattern. Depending on the impact of these variables on the training performance, we can reduce or extend the list for the future root-tuple production iterations. So I propose to store the following variables from hitPattern:
   - `numberOf(Valid|Lost)Pixel(Barrel|Endcap)Hits`, `numberOf(Valid|Lost)Strip*Hits`, `numberOf(Valid|Lost)Muon*Hits`

**Comment by shedprog** [comment]
@kandrosov from what I see: values for all numberOf(Valid|Lost)Muon*Hits-parameters are zeros (different MC are checked). Maybe it should be checked how pat::IsolatedTrack miniAOD collection is filled from generaTrack.

**Comment by kandrosov** [comment]
> @kandrosov from what I see: values for all numberOf(Valid|Lost)Muon*Hits-parameters are zeros (different MC are checked). Maybe it should be checked how pat::IsolatedTrack miniAOD collection is filled from generaTrack.

@shedprog You are right: for `isolatedTracks` originated from `packedPFCandidates` `hitPattern` values are filled with default values: [link](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATIsolatedTrackProducer.cc#L500)

While for `isolatedTracks` that have a generalTrack the pattern is taken from it [link](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATIsolatedTrackProducer.cc#L407), and since general tracks are obtained with tracker-standalone reconstruction, there is no information about hits in muon stations.

=> don't include `numberOf(Valid|Lost)Muon*Hits` in the root-tuple

**Comment by mbluj** [comment]
Hello,
a general comment: information stored in miniAOD collections is usually reduced compared to information stored in AOD counterparts even if the same data formats (e.g. hit patterns) are used. Hence several data members are set to default values, usually to 0 (zero). 
Brief documentation what is available in each object collection can be found in [this TWiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2017); all details in the relevant producer's code ;)

**Comment by kandrosov** [comment]
Thank you @mbluj! We have tried to find another way to access low-level information about hits in the muon sub-detectors using some lower-level collections (e.g. PF candidates or tracks), rather than using `pat::MuonCollection`. But in MiniAOD `pat::Muon` seems to be the only source for this kind of info. However, as far as we can access it one way or another it is not a big issue.

**Comment by mbluj** [comment]
> 
> 
> Thank you @mbluj! We have tried to find another way to access low-level information about hits in the muon sub-detectors using some lower-level collections (e.g. PF candidates or tracks), rather than using `pat::MuonCollection`. But in MiniAOD `pat::Muon` seems to be the only source for this kind of info. However, as far as we can access it one way or another it is not a big issue.

OK, I see. And, I confirm that `slimmedMuons` (`pat::MuonCollection`) is the only way to access this information. Of course one can use matching information (edm::Ref) inside `slimmedMuons` to find a packedCandidate corresponding to a given slimmedMuon, but it is not possible in other direction, i.e. packedCandidates do not contain references to muons (or electrons).
