### ISSUE TITLE
Overall checks before 2018 tuples production

### ISSUE THREAD

**Issue by kandrosov** [cms-tau-pog/TauMLTools#8]
Check that everything works and people involved in production have rights to stage out with crab to the tau POG eos area

**Comment by roger-wolf** [comment]
@rmanzoni: do you have more insights here how the rights for EOS access are set? I can also try to figure this out.

**Comment by steggema** [comment]
Via an egroup cms-eos-pog-tau, and you should be admins.

**Comment by roger-wolf** [comment]
Merci Jan! 

@kandrosov this means that you should by construction have admin rights already. You even appear twice, once as convener and once explicitly by name. Does the access work for you? Otherwise we can check the with eos managers. 

I can add now Luca, Mykyta, and whom else?

**Comment by kandrosov** [comment]
thank you @steggema and @roger-wolf ! After I was added to cms-eos-pog-tau sometime ago by @rmanzoni, I sill didn't have access. But now I have. Probably it takes a few hours (days?) to update the access DB...

**Comment by kandrosov** [comment]
> I can add now Luca, Mykyta, and whom else?

@roger-wolf thanks! maybe also Artur. Should be all for now.
